// AVIS BATCH CBORD.SEED VERSION 1.00
// AVIS FILE: BEGIN/KB/REG_MSGBOX_EXE.C
// AVIS DEPENDS:
//   - BEGIN/BEGIN.C
//   - BEGIN/KB/REG_MSGBOX.C

BEGIN.KB.REG_MSGBOX = &KB_REG_MSGBOX;
BEGIN.KB.LOG.PRINT("KB.REG_MSGBOX:READY");
