// AVIS BATCH CBORD.SEED VERSION 1.00
// AVIS FILE: BEGIN/BEGIN_EXE.C
// AVIS DEPENDS:
//   - BEGIN/BEGIN.C (must be included at global scope first)

BEGIN.LOG.PRINT("BEGIN:INI");
BEGIN.INI();

BEGIN.LOG.PRINT("BEGIN:LOAD");
BEGIN.LOAD();

BEGIN.LOG.PRINT("BEGIN:PROC");
BEGIN.PROC();

BEGIN.LOG.PRINT("BEGIN:DISPATCH");
BEGIN.DISPATCH();
