; #BGIN
; /* AVIS_COORD_DIR: VERSION/v1.04 */
; /* AVIS_COORD_FILE: bgin_jump_gate.asm */
; /* AVIS_ROLE: ASM_SOURCE_FILE */

section .rodata
    ; Jump Table: Pointers to bit-perfect bot subroutines
    align 8
    jump_table:
        dq .logic_alpha
        dq .logic_beta
        dq .logic_gamma

section .text
    global _start

_start:
    ; 1. FETCH: Obtain entropy seed from R13 (generated by bgin_random.asm)
    ; 2. NORMALIZE: Ensure index is within 0-2 (Table Bounds)
    xor rdx, rdx
    mov rax, r13
    mov rbx, 3
    div rbx                 ; RDX = Index (0, 1, or 2)

    ; 3. ROUTE: Perform Indirect Jump to scrambled node
    lea rdi, [rel jump_table]
    mov rax, [rdi + rdx*8]
    jmp rax                 ; Logic Inversion Handshake

.logic_alpha:
    ; Subroutine Alpha Pulse
    mov rdi, 10
    jmp .exit

.logic_beta:
    ; Subroutine Beta Pulse
    mov rdi, 20
    jmp .exit

.logic_gamma:
    ; Subroutine Gamma Pulse
    mov rdi, 30
    jmp .exit

.exit:
    mov rax, 60             ; sys_exit
    syscall

; #!#
