// ------------------------------------------------------------
// AVIS BATCH CBORD.SEED VERSION 1.00
// AVIS FILE: BEGIN/MASTER/MASTER_COMBINE.H
// AVIS ROLE: Master string combiner
// ------------------------------------------------------------

#ifndef MASTER_COMBINE_H
#define MASTER_COMBINE_H
#include "WIN_MAIN.H"
typedef struct _COMBINE {
    char *name;
    int   id;
} _COMBINE;

char *MASTER_COMBINE(INT_ENUM INT_SWITCH);

#endif
